### ISSUE TITLE
letsencrypt renew cronjob gets lost every now and then

### ISSUE THREAD

**Issue by arusa** [dokku/dokku-letsencrypt#215]
## Description of problem

I have 2 small dokku servers running and both have lost their letsencrypt renewal cronjobs multiple times.

I have no idea why this is happening, but I experience it on two different servers running dokku version 0.23.7 on Ubuntu 18.04 and 20.04

### Steps to Reproduce

1. Add cronjob

```
$ dokku letsencrypt:cron-job --add
no crontab for dokku
-----> Added cron job to dokku's crontab.

$ crontab -l
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
```

2. wait

3. realize that certificates did not renew and cronjob is gone

Every few months I realize that certificates will expire soon and when I go check it on the server the cronjob is suddenly gone:

```
$ dokku letsencrypt:cron-job
no crontab for dokku
       No job added. Use --add to add the cron job.

$ crontab -l
no crontab for dokku
```

#### Actual Results

Cronjobs get lost after a while

#### Expected Results

Cronjobs should remain

## Environment Information

2 Servers:

Ubuntu 18.04: dokku version 0.23.7
Ubuntu 20.04: dokku version 0.23.7

### `dokku report APP_NAME` output

The problem does not affect an app but the global letsencrypt cronjob.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Ubuntu 18.04 server:
deb https://packagecloud.io/dokku/dokku/ubuntu/ bionic main

Ubuntu 20.04 server:
deb https://packagecloud.io/dokku/dokku/ubuntu/ focal main

### Additional information

```
$ dokku plugin:list
...
  letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
...
```

Just wanted to document this problem to see if others also experience it too.

**Comment by josegonzalez** [comment]
Fuck I meant to fix this.

In a new `cron-entries` trigger, we should check the dokku version and check if it's at least a specific version - 0.23.2 - and echo out the `$SCHEDULE;$FULL_COMMAND;$ARBITRARY_DATA` (semi-colon delimited, as shown).

Also, the thing that _currently_ writes out the schedule should do the same version check, and only write if its lower than 0.23.0 (the hook was implemented in 0.23.2 but scheduled cron tasks were implemented in 0.23.0), and on versions 0.23.2 and up, trigger the `cron-write` plugin trigger.

Just writing this down in case you have time to fix it, I won't till the weekend.

**Comment by stockmind** [comment]
Same issue on my machines (dokku version updated to `0.24.0`)! 

The cron file also gets emptied out completely (clearing out even the others entries inside), and this also happens when you add the cron-job for the first time with `letsencrypt:cron-job --add`

**Comment by arusa** [comment]
I can't think of a reason why an existing crontab entry gets removed.
It would be really easy to just add this crontab entry manually, but something seems to be clearing the dokku users crontab repeatedly.

**Comment by tylercal** [comment]
I can't find the docs now, but if I recall correctly a recent release (0.23 maybe) of Dokku changed[ the way cron works](https://dokku.com/docs/processes/scheduled-cron-tasks/). I thought what I remembered reading was that if you manually maintained your crontab it would be wiped out (this is what happened for several of my non-letsencrypt cron jobs).

In any case, I'm on `0.24.2` and this will be the second time my letsencrypt cron has been wiped out in as many months.

**Comment by josegonzalez** [comment]
This was fixed, please upgrade to 0.10.0 and rerun `dokku letsencrypt:cron-job --add` to get thing working again. New deploys should also not wipe this out anymore :)

**Comment by nerg4l** [comment]
When running `dokku letsencrypt:cron-job --add` I receive the following error:

```
touch: cannot touch '/var/lib/dokku/data/letsencrypt/autorenew': No such file or directory
```

According to `plugin:list` I have the latest version:

```
letsencrypt          0.10.1 enabled    Automated installation of let's encrypt TLS certificates
```

**Comment by nerg4l** [comment]
Running `mkdir -p /var/lib/dokku/data/letsencrypt` fixed the problem but I think this should be part of the update process.

**Comment by josegonzalez** [comment]
Alright, that should be fixed now as of 0.11.0 (which also switches to `acme/lego`). If you want to try it out and verify that things worked, that'd be great.

**Comment by tylercal** [comment]
Doesn't seem to fix it for me

`letsencrypt          0.11.0 enabled`
`~> dokku letsencrypt:cron-job --add 
touch: cannot touch '/var/lib/dokku/data/letsencrypt/autorenew': No such file or directory`

**Comment by nerg4l** [comment]
Same here.

```
# dokku plugin:update letsencrypt
Plugin (letsencrypt) updated
-----> Priming bash-completion cache
# dokku letsencrypt:cron-job --add
touch: cannot touch '/var/lib/dokku/data/letsencrypt/autorenew': No such file or directory
```

```
  letsencrypt          0.11.0 enabled    Automated installation of let's encrypt TLS certificates
```

**Comment by josegonzalez** [comment]
Okay _now_ it should be fixed. We never had a symlink for the `update` trigger to the `install` trigger 😅

**Comment by josegonzalez** [comment]
Update to 0.11.1 to get the fix :)

**Comment by nerg4l** [comment]
Now it works

**Comment by tylercal** [comment]
Ditto, works for me now too. Do I remember correctly that, `dokku letsencrypt:cron-job` used to show the status of the scheduled cron job? E.g. that it had been added?

The help command shows `letsencrypt:cron-job [--add --remove]` with the square brackets making it seem like the switches are optional but the output when running without a switch, `dokku letsencrypt:cron-job`, is `Specify --add or --remove to modify the cron-job`.

The readme seems to more clearly show the switches as required, `letsencrypt:cron-job <--add|--remove>`

**Comment by josegonzalez** [comment]
Can you open a bug for current status?

**Comment by josegonzalez** [comment]
I filed the issue here: https://github.com/dokku/dokku-letsencrypt/issues/221
