### ISSUE TITLE
Bug with latest letsencrypt image

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-letsencrypt#50]
Potentially related: https://github.com/alex/letsencrypt-aws/issues/30

```
root@dokku:~# dokku letsencrypt visualcosita
=====> Let's Encrypt visualcosita...
-----> Updating letsencrypt docker image...
latest: Pulling from m3adow/letsencrypt-simp_le
420890c9e918: Already exists
acbaf1e6012f: Pull complete
5f71a1a2d3dc: Pull complete
Digest: sha256:be1d7aca214d5277af18d7bf75a2bc78afa5a1eabf98aaa8a606c4ca2a7fdeb5
Status: Downloaded newer image for m3adow/letsencrypt-simp_le:latest
       done
-----> Enabling ACME proxy for visualcosita...
-----> Getting letsencrypt certificate for visualcosita...
        - Domain 'visualcosita.dokku.josediazgonzalez.com'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-04-16 20:18:11,149:INFO:__main__:1207: Generating new account key
2016-04-16 20:18:11,830:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-16 20:18:11,999:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-16 20:18:12,192:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-16 20:18:12,498:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): letsencrypt.org
2016-04-16 20:18:13,125:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1397, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1382, in main_with_exceptions
    new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1283, in new_data
    for vhost in args.vhosts
  File "/simp_le-master/simp_le.py", line 1283, in <genexpr>
    for vhost in args.vhosts
TypeError: request_domain_challenges() got an unexpected keyword argument 'new_authzr_uri'

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for visualcosita...
       done
```

Thoughts?

**Comment by rnorth** [comment]
I've also just encountered this, running on Dokku v0.5.4 - fresh installation this evening.

**Comment by ryjen** [comment]
same with dokku 0.5.5 and letsencrypt 0.7.1

**Comment by sseemayer** [comment]
Seems that we now additionally get a problem with m3adow/letsencrypt-simp_le:

```
$ docker run --rm m3adow/letsencrypt-simp_le --test
.E.EE.....E.E.............F
======================================================================
ERROR: test_save_ignore_unpersisted (__main__.CertFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 625, in test_save_ignore_unpersisted
    self.plugin.save(self.all_data)
  File "/simp_le-master/simp_le.py", line 768, in save
    return self.save_to_file(self.dump_cert(data.cert))
  File "/simp_le-master/simp_le.py", line 459, in dump_cert
    return OpenSSL.crypto.dump_certificate(self.typ, data.wrapped).strip()
  File "/usr/lib/python2.7/site-packages/acme/jose/util.py", line 44, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'X509' object has no attribute 'wrapped'
[...]
```

Whereas simp_le running in a virtualenv is working well:
```
./simp_le.py --test
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.469s

OK
```

There is kuba/simp_le#70 and kuba/simp_le#73 suggesting the problem is caused by not running simp_le from its virtualenv which m3adow/letsencrypt-simp_le is indeed not doing. I've created m3adow/docker-letsencrypt-simp_le#1 to discuss what we can do to fix the container.

**Comment by josegonzalez** [comment]
@sseemayer may be worth us just maintaining the downstream dependencies if we don't get this resolved in the next week.

**Comment by mekwall** [comment]
Similar issue was quickly fixed over at this project: alex/letsencrypt-aws/issues/30

**Comment by sseemayer** [comment]
@mekwall were you still getting an `unexpected keyword argument 'new_authzr_uri'` error? For me, kuba/simp_le#101 fixed _that_ error and now I'm getting the aforementioned `AttributeError: 'X509' object has no attribute 'wrapped'AttributeError: 'X509' object has no attribute 'wrapped'` error in m3adow/dokku-letsencrypt-simp_le . As I wrote in m3adow/docker-letsencrypt-simp_le#1 , this could be fixed by simply re-building the image on docker hub with new dependencies.

@josegonzalez I agree that maintaining a fork ourselves will let us fix things quicker in the futurte. Would it be possible to put our version of letsencrypt-simp_le on docker hub as dokku/letsencrypt-simp_le ?

**Comment by mekwall** [comment]
@sseemayer Oh. I totally missed that one... My bad! I'll check it out!

**Comment by jimmykamau** [comment]
Any workaround for now?

**Comment by sseemayer** [comment]
If you update dokku-letsencrypt you will now use my "fork" of letsencrypt-simp_le that has a rebuilt docker image with working depencies.

**Comment by zwily** [comment]
The latest update fixed it for me.

**Comment by josegonzalez** [comment]
@sseemayer what is your docker hub name? I can add you to the docker hub org that we use (which is unfortunately not dokku...).

**Comment by sseemayer** [comment]
@josegonzales it's sseemayer too. Can I also get a fork of m3adow/docker-letsencrypt-simple in the dokku github organization? 

Too bad about the docker hub org name :/

**Comment by josegonzalez** [comment]
Both are done.

**Comment by sseemayer** [comment]
@josegonzalez can I also get admin access to the github fork? I can see the dokkupaas docker hub organization but can't seem to set up an automated build to the dokku/docker-letsencrypt-simp_le repo.

**Comment by masone** [comment]
Thanks for the quick fix guys, works again! 🎉

**Comment by josegonzalez** [comment]
Done!

**Comment by sseemayer** [comment]
OK, I've now set up the following:

- There is now the dokkupaas/letsencrypt-simp_le image on Docker Hub set up as an automatic build for the dokku/docker-letsencrypt-simp_le GitHub repository.
- I've set up a [Huginn](https://github.com/cantino/huginn) scenario to check kuba/simp_le for new commits every hour and trigger a re-build of dokkupaas/letsencrypt-simp_le if there are new simp_le commits -- this should take care of updating dependencies in the future.
- dokku-letsencrypt now uses dokkupaas/letsencrypt-simple (d5c35d7)

I'll keep sseemayer/letsencrypt-simp_le around both on Docker Hub and GitHub in order to not break things for people that don't want to update yet and will remove this in a few weeks from now.
